name: Release
on: workflow_dispatch

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    outputs:
      new_release_published: ${{ steps.semantic-release.outputs.new_release_published }}
      new_release_version: ${{ steps.semantic-release.outputs.new_release_version }}
      new_release_major_version: ${{ steps.semantic-release.outputs.new_release_major_version }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Get Configuration
        run: |
          echo "Fetching default configuration from erzz/configs..."
          curl --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --header 'Accept: application/vnd.github.v3.raw' \
            --location https://api.github.com/repos/erzz/configs/contents/configs/semantic-release-config.json \
            --fail \
            --output .releaserc.json || exit 1
          cat .releaserc.json

      - name: Semantic Release
        id: semantic-release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            conventional-changelog-conventionalcommits
            @semantic-release/exec

  floating-tag:
    name: Create floating tag
    needs: release
    if: ${{ needs.release.outputs.new_release_published == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Get Release SHA
        id: sha
        run: |
          SHA=$(git show-ref --hash v${{ needs.release.outputs.new_release_version }})
          echo "SHA for v${{ needs.release.outputs.new_release_version }}: $SHA"
          echo "sha=$SHA" >> "$GITHUB_OUTPUT"

      - name: Create floating tag
        uses: actions/github-script@v7
        env:
          SHA: ${{ steps.sha.outputs.sha }}
        with:
          github-token: ${{ secrets.RELEASE_TOKEN }}
          script: |-
            const sha = process.env.SHA;
            const major = 'v${{ needs.release.outputs.new_release_major_version }}';

            // If exists then update, else create
            try {
              await github.rest.git.updateRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `tags/${major}`,
                sha: sha,
                force: true,
              });
              core.info(`Updated ${major} to ${sha}`);
            } catch(err) {
              core.info(`Failed to update ${major}: ${err}`);
              await github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `refs/tags/${major}`,
                sha: sha,
              });
              core.info(`Created ${major} at ${sha}`);
            }
